apiVersion: apps/v1
kind: Deployment
metadata:
  name: traceops-app
  namespace: traceops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traceops-app
  template:
    metadata:
      labels:
        app: traceops-app
    spec:
      containers:
        - name: app
          image: traceops-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.traceops.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: traceops-app
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_traceidratio
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.1"
            - name: PORT
              value: "3000"
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: traceops-app
  namespace: traceops
spec:
  selector:
    app: traceops-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  type: ClusterIP
