apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traceops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/TraceOps.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: traceops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
