apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: traceops
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      debug:

      zipkin:
        endpoint: http://jaeger.traceops.svc.cluster.local:9411/api/v2/spans

      prometheus:
        endpoint: ":8889"
        const_labels:
          job: "otel-collector"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [zipkin, debug]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]